- hosts: webservers
  tasks:
   - name: 'add php repo'
     apt_repository:
      repo: 'ppa:ondrej/php'

   - name: 'update apt cache'
     apt: update_cache=yes
     become: yes

   - name: 'install nginx'
     apt:
      name: nginx
      state: present
     become: yes

   - name: 'install git'
     apt:
      name: git
      state: present
     become: yes

   - name: 'install php with extensions'
     apt:
      name:
       - php7.4
       - php7.4-fpm
       - php7.4-mysql
       - php7.4-gd
       - php-ssh2
       - php7.4-mcrypt
      state: present
     become: yes

   - name: 'config php fpm'
     replace: 'dest=/etc/php/7.4/fpm/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"'
     become: yes

   - name: 'update nginx conf for wp and php'
     template: 'src=../templates/default-site.conf dest=/etc/nginx/sites-available/{{server_name}} owner=www-data group=www-data mode=0644'
     become: yes

   - name: 'enable nginx config'
     file: 'src=/etc/nginx/sites-available/{{server_name}} dest=/etc/nginx/sites-enabled/{{server_name}} owner=www-data group=www-data state=link'
     become: yes

   - name: 'config nginx for php'
     template: src=../templates/nginx-wp-common.conf dest=/etc/nginx/nginx-wp-common.conf owner=www-data group=www-data mode=0644

   - name: 'restart nginx'
     service: 'name=nginx state=restarted'
     become: yes


