- hosts: webservers
  tasks:
   - name: 'update apt cache'
     apt: update_cache=yes
     become: yes

   - name: 'install nginx'
     apt:
      name: nginx
      state: present
     become: yes

   - name: 'install git'
     apt:
      name: git
      state: present
     become: yes

   - name: 'start nginx'
     become: yes
     service:
      name: nginx
      state: started

   - name: 'update nginx conf for wp and php'
     template: 'src=../templates/default-site.conf dest=/etc/nginx/sites-available/{{server_name}} owner=www-data group=www-data mode=0644'
     become: yes

   - name: 'enable nginx config'
     file: 'src=/etc/nginx/sites-available/{{server_name}} dest=/etc/nginx/sites-enabled/{{server_name}} owner=www-data group=www-data state=link'
     notify:
      - restart nginx
     become: yes


