- name: 'create webroot'
  file:
    state: directory
    path: /var/www
    owner: root
    group: root
    mode: 0755
  become: yes

- name: 'check wp directory'
  stat: path=/var/www/{{ server_name }}
  register: check_path

- name: 'get wp'
  get_url:
    url: https://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp/wordpress-{{ wp_version }}.tar.gz
  become: yes
  when: not check_path.stat.exists

- name: 'extract wp'
  unarchive:
    src: /tmp/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no
  become: yes
  when: not check_path.stat.exists

- name: 'move wp'
  command: mv /tmp/wordpress /var/www/{{ server_name }}
  become: yes
  when: not check_path.stat.exists

- name: 'get random salts'
  uri:
    url: 'https://api.wordpress.org/secret-key/1.1/salt/'
    return_content: yes
    method: GET
  register: 'wp_salt'

- name: 'create wp config'
  template: "src=../templates/wp-config.php dest=/var/www/{{ server_name }}/wp-config.php"
  become: yes

- name: 'update wp config'
  lineinfile:
    dest: "/var/www/{{ server_name }}/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ wp_db_name }}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ wp_user }}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ wp_pass }}');"}
  become: yes
